project:
  type: website

website:
  title: "Awsome Tables using {gt}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - getting Start.qmd
      - tableexport.qmd
      - modify.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

